version: '3'

services:
  quill:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./.deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.deploy/nginx/production.nginx:/etc/nginx/conf.d/default.conf
      - ./.deploy/certbot/conf:/etc/letsencrypt
      - ./.deploy/certbot/www:/var/www/certbot
      - static:/srv/playground/.static
    depends_on:
      - django
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - default
      - proxy

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - default

  django:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    volumes:
      - static:/srv/playground/.static
    command: bash -c '
      python manage.py collectstatic --noinput &&
      python manage.py migrate --noinput &&
      gunicorn -c /srv/.deploy/gunicorn.py config.wsgi'
    networks:
      - default

volumes:
  static:

networks:
  default:
  proxy:
    external: true
