version: '3'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./.deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.deploy/nginx/local.nginx:/etc/nginx/conf.d/default.conf
      - static:/srv/playground/.static
    command: "/bin/sh -c 'nginx -g \"daemon off;\"'"
    ports:
      - 8000:80
      - 443:443

  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/srv/playground/.static
    command: bash -c '
      python manage.py collectstatic --noinput &&
      python manage.py migrate --noinput &&
      gunicorn -c /srv/.deploy/gunicorn.py config.wsgi'

volumes:
  static:
