version: '3'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./.deploy/nginx/local.nginx:/etc/nginx/conf.d/default.conf
      - static:/srv/playground/.static
    ports:
      - 8000:80
      - 443:443

  django:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        requirements: requirements.txt
    volumes:
      - static:/srv/playground/.static
    command: bash -c '
      python manage.py collectstatic --noinput &&
      python manage.py migrate --noinput &&
      gunicorn -c /srv/.deploy/gunicorn.py config.wsgi'

volumes:
  static:
